def build(bld):
  bld.objects( source    = bld.path.ant_glob('*.c'),
                includes  = '. ../../..',
                features  = 'c',
                use       = 'opt',
                target    = 'metis_objs',
             )
  bld.contrib_objs.append('metis_objs')

