def build(bld):
  bld.objects( source    = bld.path.ant_glob('*.cc'),
                includes  = '. ../../..',
                features  = 'cxx',
                use       = 'opt',
                target    = 'expreval_objs',
             )
  bld.contrib_objs.append('expreval_objs')

