import os
import sipconfig

# The name of the SIP build file generated by SIP and used by the build
# system.
build_file = "PMI_benchmark_optical.sbf"

# Get the SIP configuration information.
config = sipconfig.Configuration()

# Run SIP to generate the code.
os.system(" ".join([config.sip_bin, "-c", ".", "-b", build_file, "-I", "../include", "PMI_benchmark_optical.sip"]))

# Create the Makefile.

makefile = sipconfig.SIPModuleMakefile(config, build_file)


makefile.extra_include_dirs=["..", "../include"]

# Add the library we are wrapping.  The name doesn't include any platform
# specific prefixes or extensions (e.g. the "lib" prefix on UNIX, or the
# ".dll" extension on Windows).
makefile.extra_lib_dirs=[".."]
makefile.extra_libs=["PMIBenchmarkOptical"]

# Generate the Makefile itself.
makefile.generate()

