all:
	./configure.py
	(cd build; make)

install:
	(cd build; make install)
	cp src/geniusd.py ../bin/
	cp src/test.py ../bin/
	cp src/GeniusCtrl.py ../bin/
	cp src/GeniusLib.py ../bin/
	cp src/HTTPFE.py ../bin/

